#!/bin/sh
SCRIPTPATH=$(dirname $0)
node $SCRIPTPATH/src/inode_server.js > /dev/null 2>&1 &
sleep 1
node $SCRIPTPATH/src/inode_client.js
# kill background node
trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT
